#!/bin/sh

# Set these paths appropriately

BIN="/f/python/secondKursAdwiser/SecondKursAdw/website/tt/bin"
CMD="/f/python/secondKursAdwiser/SecondKursAdw/website/tt/cmd"
LIB="/f/python/secondKursAdwiser/SecondKursAdw/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/danish-abbreviations
PARFILE=${LIB}/danish.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
