#!/bin/sh

# Set these paths appropriately

BIN="/f/python/secondKursAdwiser/SecondKursAdw/website/tt/bin"
CMD="/f/python/secondKursAdwiser/SecondKursAdw/website/tt/cmd"
LIB="/f/python/secondKursAdwiser/SecondKursAdw/website/tt/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
