#!/bin/sh

# Set these paths appropriately

BIN="/f/python/ADWISER/website/tt/bin"
CMD="/f/python/ADWISER/website/tt/cmd"
LIB="/f/python/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/old-french-abbreviations
PARFILE=${LIB}/old-french.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
